version: '2.4'
services:
    obu:
        hostname: obu
        container_name: obu1
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=101
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:01:00
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.11
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    obu2:
        hostname: obu2
        container_name: obu2
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=102
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:02:00
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.12
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    obu3:
        hostname: obu3
        container_name: obu3
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=103
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:03:00
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.13
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    obu4:
        hostname: obu4
        container_name: obu4
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=104
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:04:00
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.14
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    obu5:
        hostname: obu5
        container_name: obu5
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=105
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:05:00
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.15
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu1:
        hostname: rsu1
        container_name: rsu1
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu6:
        hostname: rsu6
        container_name: rsu6
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=6
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:06
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.60
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536
    
    rsu10:
        hostname: rsu10
        container_name: rsu10
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=10
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:10
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.100
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu11:
        hostname: rsu11
        container_name: rsu11
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=11
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:11
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.110
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu13:
        hostname: rsu13
        container_name: rsu13
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=13
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:13
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.130
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu15:
        hostname: rsu15
        container_name: rsu15
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=15
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:15
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.150
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu16:
        hostname: rsu16
        container_name: rsu16
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=16
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:16
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.160
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu19:
        hostname: rsu19
        container_name: rsu19
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=19
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:19
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.190
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu22:
        hostname: rsu22
        container_name: rsu22
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=22
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:22
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.220
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu25:
        hostname: rsu25
        container_name: rsu25
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=25
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:25
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.25
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu28:
        hostname: rsu28
        container_name: rsu28
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=28
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:28
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.28
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu30:
        hostname: rsu30
        container_name: rsu30
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=30
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:30
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.230
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu34:
        hostname: rsu34
        container_name: rsu34
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=34
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:34
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.234
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu36:
        hostname: rsu36
        container_name: rsu36
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=36
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:36
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.236
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu38:
        hostname: rsu38
        container_name: rsu38
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=38
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:38
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.238
        sysctls:
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

networks:
  vanetzalan0:
    external: true
